export const REPORT_COLORS = {
    DARK_GREEN: "#105E4A",
    GREEN: "#22A274",
    RED: "#E83A55",
    DARK_RED: "#742A3B",
    TEAL: "#0D6762",
    BLUE: "#255CA6",
    VIOLET: "#3C1A66",
    OLIVE: "#654E0E",
    MAGENTA: "#8E3078",
    LIGHT_BLUE: "#306A8E",
    LIGHT_GREEN: "#548E30",
    ROSE_GOLD: "#8E6230",
    MUTED_AZURE: "#324C52"
}

const STANDARD_ANSWERS = {
    "STRONGLY_FOR": "Zdecydowanie za",
    "FOR": "Za",
    "NOT_SURE": "Nie wiem",
    "AGAINST": "Przeciw",
    "STRONGLY_AGAINST": "Zdecydowanie przeciw",
    "NO_ANSWER": "Brak odpowiedzi",
    "FOR_OR_STRONGLY_FOR": "Poparcie",
    "AGAINST_OR_STRONGLY_AGAINST": "Sprzeciw",
}

export const STANDARD_GROUP_ANSWERS = {
    [STANDARD_ANSWERS.FOR_OR_STRONGLY_FOR]: [STANDARD_ANSWERS.FOR, STANDARD_ANSWERS.STRONGLY_FOR],
    [STANDARD_ANSWERS.AGAINST_OR_STRONGLY_AGAINST]: [STANDARD_ANSWERS.AGAINST, STANDARD_ANSWERS.STRONGLY_AGAINST],
}

export const REPORT_ANSWERS_ORDER = {
    "default": -1,
    [STANDARD_ANSWERS.FOR_OR_STRONGLY_FOR]: 0,
    [STANDARD_ANSWERS.STRONGLY_FOR]: 0,
    [STANDARD_ANSWERS.FOR]: 1,
    [STANDARD_ANSWERS.NOT_SURE]: 2,
    [STANDARD_ANSWERS.AGAINST]: 3,
    [STANDARD_ANSWERS.STRONGLY_AGAINST]: 4,
    [STANDARD_ANSWERS.AGAINST_OR_STRONGLY_AGAINST]: 4,
    [STANDARD_ANSWERS.NO_ANSWER]: 5,
}

export const REPORT_ANSWER_COLORS = {
    [STANDARD_ANSWERS.STRONGLY_FOR]: REPORT_COLORS.DARK_GREEN,
    [STANDARD_ANSWERS.FOR_OR_STRONGLY_FOR]: REPORT_COLORS.GREEN,
    [STANDARD_ANSWERS.FOR]: REPORT_COLORS.GREEN,
    [STANDARD_ANSWERS.AGAINST]: REPORT_COLORS.RED,
    [STANDARD_ANSWERS.AGAINST_OR_STRONGLY_AGAINST]: REPORT_COLORS.RED,
    [STANDARD_ANSWERS.STRONGLY_AGAINST]: REPORT_COLORS.DARK_RED,
    [STANDARD_ANSWERS.NOT_SURE]: REPORT_COLORS.MUTED_AZURE,
    [STANDARD_ANSWERS.NO_ANSWER]: REPORT_COLORS.MUTED_AZURE,
}

export const REPORT_NON_STANDARD_ANSWER_COLORS_ORDER: Record<string, string> = {
    "0": REPORT_COLORS.BLUE,
    "1": REPORT_COLORS.TEAL,
    "2": REPORT_COLORS.VIOLET,
    "3": REPORT_COLORS.OLIVE,
    "4": REPORT_COLORS.MAGENTA,
    "5": REPORT_COLORS.LIGHT_BLUE,
    "6": REPORT_COLORS.LIGHT_GREEN,
    "7": REPORT_COLORS.ROSE_GOLD,
    "8": REPORT_COLORS.MUTED_AZURE,
    "9": REPORT_COLORS.DARK_GREEN,
    "10": REPORT_COLORS.GREEN,
    "11": REPORT_COLORS.RED,
    "12": REPORT_COLORS.DARK_RED,
}